name: Transcribe Audio

on:
  workflow_dispatch:
    inputs:
      input_path:
        description: 'File or directory to transcribe (optional)'
        required: false
        default: '.'
      language:
        type: choice
        description: 'Language (code - name, or auto)'
        options:
          - auto - Auto-detect
          - af - Afrikaans
          - am - Amharic
          - ar - Arabic
          - as - Assamese
          - az - Azerbaijani
          - be - Belarusian
          - bg - Bulgarian
          - bn - Bengali
          - bo - Tibetan
          - bs - Bosnian
          - ca - Catalan
          - cs - Czech
          - cy - Welsh
          - da - Danish
          - de - German
          - el - Greek
          - en - English
          - eo - Esperanto
          - es - Spanish
          - et - Estonian
          - eu - Basque
          - fa - Persian
          - fi - Finnish
          - fo - Faroese
          - fr - French
          - gl - Galician
          - gu - Gujarati
          - ha - Hausa
          - haw - Hawaiian
          - he - Hebrew
          - hi - Hindi
          - hr - Croatian
          - ht - Haitian Creole
          - hu - Hungarian
          - hy - Armenian
          - id - Indonesian
          - is - Icelandic
          - it - Italian
          - ja - Japanese
          - jv - Javanese
          - ka - Georgian
          - kk - Kazakh
          - km - Khmer
          - kn - Kannada
          - ko - Korean
          - la - Latin
          - lb - Luxembourgish
          - ln - Lingala
          - lo - Lao
          - lt - Lithuanian
          - lv - Latvian
          - mg - Malagasy
          - mk - Macedonian
          - ml - Malayalam
          - mn - Mongolian
          - mr - Marathi
          - ms - Malay
          - mt - Maltese
          - my - Burmese
          - ne - Nepali
          - nl - Dutch
          - nn - Norwegian Nynorsk
          - no - Norwegian
          - oc - Occitan
          - pa - Punjabi
          - pl - Polish
          - ps - Pashto
          - pt - Portuguese
          - ro - Romanian
          - ru - Russian
          - sa - Sanskrit
          - sd - Sindhi
          - si - Sinhala
          - sk - Slovak
          - sl - Slovenian
          - sn - Shona
          - so - Somali
          - sq - Albanian
          - sr - Serbian
          - su - Sundanese
          - sv - Swedish
          - sw - Swahili
          - ta - Tamil
          - te - Telugu
          - tg - Tajik
          - th - Thai
          - tk - Turkmen
          - tl - Tagalog
          - tr - Turkish
          - tt - Tatar
          - uk - Ukrainian
          - ur - Urdu
          - uz - Uzbek
          - vi - Vietnamese
          - yi - Yiddish
          - yo - Yoruba
          - zh - Chinese
        required: false
        default: auto - Auto-detect
      model:
        type: choice
        description: 'Whisper model to use'
        options:
          - tiny
          - base
          - small
          - medium
          - large-v3
        required: false
        default: medium
  push:
    paths:
      - '**/*.mp3'
      - '**/*.wav'
      - '**/*.m4a'
      - '**/*.mp4'
      - '**/*.mpeg'
      - '**/*.mpga'
      - '**/*.webm'
      - '**/*.ogg'
      - '**/*.flac'
      - 'transcribe.py'
      - 'requirements.txt'

permissions:
  contents: write

jobs:
  transcribe:
    runs-on: ubuntu-latest
    env:
      INPUT_PATH: ${{ github.event.inputs.input_path }}
      MODEL: ${{ github.event.inputs.model }}
      LANGUAGE: ${{ github.event.inputs.language }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies (torch CPU + whisper)
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision torchaudio
          pip install -r requirements.txt

      - name: Transcribe audio files
        run: |
          set -e
          INPUT_ARG="${INPUT_PATH:-.}"
          MODEL_ARG="${MODEL:-medium}"
          LANG_ARG="${LANGUAGE:-}"
          # Extract language code from option like "en - English"
          LANG_CODE="$LANG_ARG"
          if [ -n "$LANG_CODE" ]; then
            LANG_CODE=${LANG_CODE%% *}
          fi
          if [ -n "$LANG_CODE" ] && [ "$LANG_CODE" != "auto" ]; then
            python transcribe.py --input "$INPUT_ARG" --out-dir transcripts --model "$MODEL_ARG" --language "$LANG_CODE" --formats txt,json,srt,vtt
          else
            python transcribe.py --input "$INPUT_ARG" --out-dir transcripts --model "$MODEL_ARG" --formats txt,json,srt,vtt
          fi

      - name: Upload transcripts as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: transcripts
          path: transcripts
          if-no-files-found: warn

      - name: Commit transcripts back to repo
        if: success()
        run: |
          if [ -d transcripts ] && [ -n "$(git status --porcelain transcripts)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add transcripts
            git commit -m "Add/update transcripts [skip ci]"
            git push
          else
            echo "No transcript changes to commit."
          fi
